---
title: Beat
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@domain.com
description: 'TBD.'

baseurl:
url:
twitter_username: voxmedia
github_username: voxmedia
permalink: "/projects/:title.html"
markdown: kramdown
includes:
- svgs
gems:
- jekyll-feed
- jekyll-autoprefixer
exclude:
- Gemfile
- Gemfile.lock
